import rostrum.buildlogic.CargoNdkBuild
import rostrum.buildlogic.ReleaseSigning
import rostrum.buildlogic.UniffiBindgen
import rostrum.buildlogic.cargoExecutable
import rostrum.buildlogic.ndkDirectory

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

// --- Rust (see docs/features/android_build.md) ------------------------------
// The cargo workspace is the repository root, one level above `android/`.
val rustWorkspace: Directory = layout.projectDirectory.dir(rootDir.parentFile.absolutePath)
val ffiPackage = "rostrum-ffi"
val ffiLibrary = "librostrum_ffi.so"
val androidAbis = listOf("arm64-v8a", "x86_64")
val rustJniLibsDir: Provider<Directory> = layout.buildDirectory.dir("rustJniLibs")
val uniffiKotlinDir: Provider<Directory> = layout.buildDirectory.dir("generated/source/uniffi/kotlin")

val cargoNdkBuild = tasks.register<CargoNdkBuild>("cargoNdkBuild") {
    group = "rust"
    description = "Builds $ffiLibrary for ${androidAbis.joinToString()} with cargo-ndk."
    cargo = providers.cargoExecutable()
    ndkDir = providers.ndkDirectory(rootProject.layout.projectDirectory, libs.versions.ndk.get())
    packageName = ffiPackage
    profile = providers.gradleProperty("rostrum.cargoProfile")
    abis = androidAbis
    apiLevel = libs.versions.minSdk.get().toInt()
    workspaceDir = rustWorkspace
    sources.from(
        rustWorkspace.file("Cargo.toml"),
        rustWorkspace.file("Cargo.lock"),
        rustWorkspace.dir("crates").asFileTree.matching { exclude("**/target/**") },
    )
    outputDir = rustJniLibsDir
}

val uniffiBindgen = tasks.register<UniffiBindgen>("uniffiBindgen") {
    group = "rust"
    description = "Generates the Kotlin bindings for $ffiLibrary with uniffi-bindgen."
    cargo = providers.cargoExecutable()
    packageName = ffiPackage
    workspaceDir = rustWorkspace
    library = cargoNdkBuild.flatMap { it.outputDir.file("${androidAbis.first()}/$ffiLibrary") }
    configFiles.from(rustWorkspace.file("Cargo.lock"), rustWorkspace.file("crates/$ffiPackage/uniffi.toml"))
    outputDir = uniffiKotlinDir
}

tasks.named("preBuild") { dependsOn(cargoNdkBuild, uniffiBindgen) }

// --- Host smoke tests -----------------------------------------------------------
// JVM tests that drive the real generated bindings, loading librostrum_ffi.so
// built for this machine (target/debug) through JNA's desktop jar. Tagged, so
// the normal unit test run skips them; see docs/features/android_app.md.
val hostLibraryDir: Directory = rustWorkspace.dir("target/debug")

val cargoHostBuild = tasks.register<Exec>("cargoHostBuild") {
    group = "rust"
    description = "Builds $ffiLibrary for the build machine, for the host smoke tests."
    workingDir = rustWorkspace.asFile
    commandLine(providers.cargoExecutable().get(), "build", "--locked", "--lib", "-p", ffiPackage)
    // cargo's own fingerprinting decides what to rebuild.
    outputs.upToDateWhen { false }
}

/** A Test task over the debug unit tests' classes, running only [tag]. */
fun registerHostTests(name: String, tag: String, summary: String) = tasks.register<Test>(name) {
    group = "verification"
    description = summary
    val unitTests = tasks.getByName<Test>("testDebugUnitTest")
    testClassesDirs = unitTests.testClassesDirs
    classpath = unitTests.classpath
    useJUnitPlatform { includeTags(tag) }
    systemProperty("jna.library.path", hostLibraryDir.asFile.absolutePath)
    systemProperty("rostrum.hostTests", "true")
    dependsOn(cargoHostBuild)
    outputs.upToDateWhen { false }
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
}

registerHostTests(
    "hostSmokeTest", "host-smoke",
    "Drives FfiRostrumBackend over the real core built for this machine (no network).",
)
registerHostTests(
    "liveDesktopCheck", "live-desktop",
    "Pairs with the rostrumd on this machine (ROSTRUM_LIVE_PAIR_URI_FILE) and unpairs. Run by hand, never in CI.",
)

// --- Signing ----------------------------------------------------------------
val releaseSigning = ReleaseSigning.load(rootProject.file(".env")) { providers.environmentVariable(it).orNull }

android {
    namespace = "io.github.rhizonymph.rostrum"
    compileSdk = libs.versions.compileSdk.get().toInt()
    // Used by AGP to strip librostrum_ffi.so when packaging (the cargo profile
    // keeps its symbol table for uniffi-bindgen).
    ndkVersion = libs.versions.ndk.get()

    defaultConfig {
        applicationId = "io.github.rhizonymph.rostrum"
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = 6
        versionName = "0.1.0"
        ndk { abiFilters += androidAbis }
    }

    // Generated by the tasks above; `preBuild` depends on both.
    sourceSets.getByName("main") {
        jniLibs.directories += rustJniLibsDir.get().asFile.absolutePath
        kotlin.directories += uniffiKotlinDir.get().asFile.absolutePath
    }

    signingConfigs {
        if (releaseSigning is ReleaseSigning.Keystore) {
            create("release") {
                storeFile = releaseSigning.storeFile
                storePassword = releaseSigning.storePassword
                keyAlias = releaseSigning.keyAlias
                keyPassword = releaseSigning.keyPassword
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = when (releaseSigning) {
                is ReleaseSigning.Keystore -> signingConfigs.getByName("release")
                is ReleaseSigning.Unavailable -> {
                    logger.warn("warning: release build is signed with the DEBUG key: ${releaseSigning.reason}")
                    signingConfigs.getByName("debug")
                }
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    buildFeatures {
        compose = true
    }

    testOptions {
        unitTests {
            // android.util.Log and friends return defaults instead of throwing,
            // so ViewModels and the data layer run on the plain JVM.
            isReturnDefaultValues = true
            // Host smoke and live-desktop tests need the host library; they
            // run from their own tasks (see "Host smoke tests" above).
            all { it.useJUnitPlatform { excludeTags("host-smoke", "live-desktop") } }
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.foundation)
    implementation(libs.compose.material3)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.kotlinx.serialization.core)

    // Required by the generated UniFFI bindings (async exports, native calls).
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.jna) {
        // The AAR, not the JAR: it carries jni/<abi>/libjnidispatch.so.
        artifact { type = "aar" }
    }

    // The JAR, for the host smoke tests: it carries libjnidispatch for the
    // build machine (the AAR above only has Android's).
    testImplementation(libs.jna)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testRuntimeOnly(libs.junit.platform.launcher)
}
